=== zebrajaeger/jsphere2cube/core/src/main/resources/de/zebrajaeger/sphere2cube/config/sphere2cube.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "debug": {
      "type": "boolean"
    },
    "source": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ]
    },
    "target": {
      "type": "string"
    },
    "preview": {
      "type": "object",
      "properties": {
        "cubemap": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "edge": {
              "type": "integer"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "edge",
            "target"
          ]
        },
        "equirectangular": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "edge": {
              "type": "integer"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "edge",
            "target"
          ]
        },
        "scaled": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "edge": {
              "type": "integer"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "edge",
            "target"
          ]
        }
      },
      "required": [
        "cubemap",
        "equirectangular",
        "scaled"
      ]
    },
    "cubemap": {
      "type": "object",
      "properties": {
        "tiles": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "tileEdge": {
              "type": "integer"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "tileEdge",
            "target"
          ]
        },
        "faces": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "target": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "target"
          ]
        }
      },
      "required": [
        "tiles",
        "faces"
      ]
    },
    "viewer": {
      "type": "object",
      "properties": {
        "pannellum": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "title": {
              "type": "string"
            },
            "target": {
              "type": "string"
            },
            "js": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "css": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "enabled",
            "title",
            "target",
            "js",
            "css"
          ]
        },
        "marzipano": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "title": {
              "type": "string"
            },
            "target": {
              "type": "string"
            },
            "js": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "css": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "enabled",
            "title",
            "target",
            "js",
            "css"
          ]
        }
      },
      "required": [
        "pannellum",
        "marzipano"
      ]
    },
    "archive": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "target": {
          "type": "string"
        }
      },
      "required": [
        "enabled",
        "target"
      ]
    }
  },
  "required": [
    "debug",
    "source",
    "target",
    "preview",
    "cubemap",
    "viewer",
    "archive"
  ]
}

=== zebrajaeger/jsphere2cube/config.example.json
{
  "debug": false,
  "source": {
    "path": "PATH TO YOUR PANO IMAGE"
  },
  "target": "./build",
  "preview": {
    "cubemap": {
      "enabled": true,
      "edge": 200,
      "target": "preview_cube.jpg"
    },
    "equirectangular": {
      "enabled": true,
      "edge": 800,
      "target": "preview_equirectangular.jpg"
    },
    "scaled": {
      "enabled": true,
      "edge": 800,
      "target": "preview_scaled.jpg"
    }
  },
  "cubemap": {
    "tiles": {
      "enabled": true,
      "tileEdge": 512,
      "target": "{{levelCount}}/{{faceNameShortLowerCase}}{{xIndex}}_{{yIndex}}.png"
    },
    "faces": {
      "enabled": false,
      "target": "{{faceNameLowerCase}}_{{levelCount}}.png"
    }
  },
  "viewer": {
    "pannellum": {
      "enabled": true,
      "title": "cube2sphere - Pannellum",
      "target": "index.p.html",
      "js": [
        "https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"
      ],
      "css": [
        "https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"
      ]
    },
    "marzipano": {
      "enabled": true,
      "title": "cube2sphere - Marzipano",
      "target": "index.m.html",
      "js": [
        "https://cdn.jsdelivr.net/npm/marzipano@0.10.2/dist/marzipano.min.js"
      ],
      "css": [
        "https://www.marzipano.net/demos/sample-tour/style.css"
      ]
    }
  },
  "archive": {
    "enabled": true,
    "target": "pano.zip"
  }
}
